name: Build

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: checkout project
      uses: actions/checkout@v2

    - name: setup msbuild
      uses: microsoft/setup-msbuild@v1

    - name: setup nuget
      uses: NuGet/setup-nuget@v1.0.2

    - name: setup cppwinrt
      run: nuget restore src/test.sln

    - name: build x86
      run: msbuild /m /p:Configuration=Release,Platform=x86 src/test.sln

    - name: build x64
      run: msbuild /m /p:Configuration=Release,Platform=x64 src/test.sln

    - name: nuget pack
      run: nuget.exe pack src/Test.nuspec -OutputFileNamesWithoutVersion

    - name: nuget push
      run: nuget push -source "GitHub" Microsoft.Windows.RustTestWinRT.nupkg
